### ISSUE TITLE
[Android] Crash with v3.1.0 on RN 68

### ISSUE THREAD

**Issue by jonathanmos** [iamolegga/react-native-launch-arguments#40]
App is crashing with the following error in the adb log when I include react-native-launch-arguments v3.1.0. Removing the import fixes the issue. What could be the problem?

Environment info:
Android emulator with api 29
react-native: 0.68.2
node: 14.9.1

```
AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'value' of null, js engine: hermes, stack:
AndroidRuntime: anonymous@1:24459
AndroidRuntime: loadModuleImplementation@1:15724
AndroidRuntime: guardedLoadModule@1:15273
AndroidRuntime: metroRequire@1:14901
AndroidRuntime: anonymous@1:22226
AndroidRuntime: loadModuleImplementation@1:15724
AndroidRuntime: guardedLoadModule@1:15230
AndroidRuntime: metroRequire@1:14901
AndroidRuntime: global@1:14487
AndroidRuntime:
AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by iamolegga** [comment]
Please retry with the version `4.0.3`
